default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rst
  username: rst
  password: password1

test:
  <<: *default
  database: rst
  username: rst
  password: password1


