# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5776a03f6ab86cec58c3e9308cce10e42a0523d01bb828d628ce673b12b93a60b8e495ff9b230134d06ba771affc4b22eeab5416cbc85d48d0cbdfecb1285eda

test:
  secret_key_base: 2ea6abdbdacaeeb0be86a800c4f7d0204393f38ddedc12b0d134518fd87bf543ddd007c658e201069410d435598d43f88816f0c1c1a5dbcc58122fd700686e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
